"""Add missing columns to activity_logs and materials

Revision ID: 1653e3fcec3c
Revises: b6456a87f56d
Create Date: 2025-12-16 21:07:30.027795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1653e3fcec3c'
down_revision: Union[str, None] = 'b6456a87f56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_materials_course', table_name='course_materials')
    op.drop_index('ix_course_materials_course_id', table_name='course_materials')
    op.drop_index('ix_course_materials_id', table_name='course_materials')
    op.drop_index('ix_course_materials_title', table_name='course_materials')
    op.drop_index('ix_course_materials_uploaded_by', table_name='course_materials')
    op.drop_index('ix_course_materials_uploader', table_name='course_materials')
    op.drop_table('course_materials')
    op.add_column('activity_logs', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_activity_logs_course_id'), 'activity_logs', ['course_id'], unique=False)
    op.create_foreign_key(None, 'activity_logs', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.add_column('materials', sa.Column('material_type', sa.String(length=20), nullable=False, server_default='crawled'))
    op.add_column('materials', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('file_path', sa.String(length=512), nullable=True))
    op.add_column('materials', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('download_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('materials', sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('materials', sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('materials', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('materials', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index('ix_materials_content_hash', table_name='materials')
    op.drop_index('ix_materials_url', table_name='materials')
    op.create_index(op.f('ix_materials_url'), 'materials', ['url'], unique=False)
    op.create_index('ix_materials_material_type', 'materials', ['material_type'], unique=False)
    op.create_index('ix_materials_uploaded_by', 'materials', ['uploaded_by'], unique=False)
    op.create_unique_constraint(None, 'materials', ['file_path'])
    op.create_foreign_key(None, 'materials', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='unique')
    op.drop_index('ix_materials_uploaded_by', table_name='materials')
    op.drop_index('ix_materials_material_type', table_name='materials')
    op.drop_index(op.f('ix_materials_url'), table_name='materials')
    op.create_index('ix_materials_url', 'materials', ['url'], unique=True)
    op.create_index('ix_materials_content_hash', 'materials', ['content_hash'], unique=False)
    op.alter_column('materials', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('materials', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('materials', 'last_downloaded_at')
    op.drop_column('materials', 'view_count')
    op.drop_column('materials', 'download_count')
    op.drop_column('materials', 'content_type')
    op.drop_column('materials', 'file_size')
    op.drop_column('materials', 'file_path')
    op.drop_column('materials', 'file_name')
    op.drop_column('materials', 'uploaded_by')
    op.drop_column('materials', 'material_type')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_activity_logs_course_id'), table_name='activity_logs')
    op.drop_column('activity_logs', 'course_id')
    op.create_table('course_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_downloaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_materials_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='course_materials_uploaded_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='course_materials_pkey'),
    sa.UniqueConstraint('file_path', name='course_materials_file_path_key')
    )
    op.create_index('ix_course_materials_uploader', 'course_materials', ['uploaded_by'], unique=False)
    op.create_index('ix_course_materials_uploaded_by', 'course_materials', ['uploaded_by'], unique=False)
    op.create_index('ix_course_materials_title', 'course_materials', ['title'], unique=False)
    op.create_index('ix_course_materials_id', 'course_materials', ['id'], unique=False)
    op.create_index('ix_course_materials_course_id', 'course_materials', ['course_id'], unique=False)
    op.create_index('ix_course_materials_course', 'course_materials', ['course_id'], unique=False)
    # ### end Alembic commands ###
