"""Add analytics fields to course_materials

Revision ID: 6370c1e0b595
Revises: 98605e1211b2
Create Date: 2025-12-12 10:41:08.974565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6370c1e0b595'
down_revision: Union[str, None] = '98605e1211b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('download_count', sa.Integer(), nullable=False))
    op.add_column('course_materials', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('course_materials', sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'last_downloaded_at')
    op.drop_column('course_materials', 'view_count')
    op.drop_column('course_materials', 'download_count')
    # ### end Alembic commands ###
