"""add material tables and update syllabus indexes

Revision ID: 8e38b33c6342
Revises: 4674adc808f1
Create Date: 2025-12-07 11:44:12.619134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import JSON

# revision identifiers, used by Alembic.
revision: str = '8e38b33c6342'
down_revision: Union[str, None] = '4674adc808f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawler_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_crawler_type'), 'crawl_logs', ['crawler_type'], unique=False)
    op.create_index(op.f('ix_crawl_logs_id'), 'crawl_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_logs_status'), 'crawl_logs', ['status'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quality_score >= 0.0 AND quality_score <= 1.0', name='check_quality_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_content_hash'), 'materials', ['content_hash'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_quality_score'), 'materials', ['quality_score'], unique=False)
    op.create_index(op.f('ix_materials_source'), 'materials', ['source'], unique=False)
    op.create_index(op.f('ix_materials_title'), 'materials', ['title'], unique=False)
    op.create_index('ix_materials_type', 'materials', ['type'], unique=False)
    op.create_index(op.f('ix_materials_url'), 'materials', ['url'], unique=True)
    op.create_table('material_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('approved_by_lecturer', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('relevance_score >= 0.0 AND relevance_score <= 1.0', name='check_relevance_score_range'),
    sa.CheckConstraint('week_number BETWEEN 1 AND 14', name='check_material_topic_week_range'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_topics_course_id'), 'material_topics', ['course_id'], unique=False)
    op.create_index('ix_material_topics_course_week', 'material_topics', ['course_id', 'week_number'], unique=False)
    op.create_index(op.f('ix_material_topics_id'), 'material_topics', ['id'], unique=False)
    op.create_index('ix_material_topics_material', 'material_topics', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_topics_material_id'), 'material_topics', ['material_id'], unique=False)
    op.alter_column('courses', 'lecturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_courses_lecturer_id'), 'courses', ['lecturer_id'], unique=False)
    op.drop_constraint('courses_lecturer_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['lecturer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('syllabus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_syllabus_course_id'), 'syllabus', ['course_id'], unique=False)
    op.create_index('ix_syllabus_course_week', 'syllabus', ['course_id', 'week_number'], unique=False)
    op.create_index(op.f('ix_syllabus_created_by'), 'syllabus', ['created_by'], unique=False)
    op.create_index(op.f('ix_syllabus_week_number'), 'syllabus', ['week_number'], unique=False)
    op.drop_constraint('syllabus_created_by_fkey', 'syllabus', type_='foreignkey')
    op.create_foreign_key(None, 'syllabus', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'syllabus', type_='foreignkey')
    op.create_foreign_key('syllabus_created_by_fkey', 'syllabus', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_syllabus_week_number'), table_name='syllabus')
    op.drop_index(op.f('ix_syllabus_created_by'), table_name='syllabus')
    op.drop_index('ix_syllabus_course_week', table_name='syllabus')
    op.drop_index(op.f('ix_syllabus_course_id'), table_name='syllabus')
    op.alter_column('syllabus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_lecturer_id_fkey', 'courses', 'users', ['lecturer_id'], ['id'])
    op.drop_index(op.f('ix_courses_lecturer_id'), table_name='courses')
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'lecturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_material_topics_material_id'), table_name='material_topics')
    op.drop_index('ix_material_topics_material', table_name='material_topics')
    op.drop_index(op.f('ix_material_topics_id'), table_name='material_topics')
    op.drop_index('ix_material_topics_course_week', table_name='material_topics')
    op.drop_index(op.f('ix_material_topics_course_id'), table_name='material_topics')
    op.drop_table('material_topics')
    op.drop_index(op.f('ix_materials_url'), table_name='materials')
    op.drop_index('ix_materials_type', table_name='materials')
    op.drop_index(op.f('ix_materials_title'), table_name='materials')
    op.drop_index(op.f('ix_materials_source'), table_name='materials')
    op.drop_index(op.f('ix_materials_quality_score'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_content_hash'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_crawl_logs_status'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_id'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_crawler_type'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    # ### end Alembic commands ###
