"""Add course_materials table for manual uploads

Revision ID: 98605e1211b2
Revises: 148c292cd2e9
Create Date: 2025-12-12 10:28:54.373677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98605e1211b2'
down_revision: Union[str, None] = '148c292cd2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('ix_course_materials_course', 'course_materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_materials_course_id'), 'course_materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_materials_id'), 'course_materials', ['id'], unique=False)
    op.create_index(op.f('ix_course_materials_title'), 'course_materials', ['title'], unique=False)
    op.create_index(op.f('ix_course_materials_uploaded_by'), 'course_materials', ['uploaded_by'], unique=False)
    op.create_index('ix_course_materials_uploader', 'course_materials', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_course_id'), 'learning_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_student_id'), 'learning_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_material_ratings_id'), 'material_ratings', ['id'], unique=False)
    op.drop_index(op.f('ix_material_topics_material_id'), table_name='material_topics')
    op.alter_column('materials', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_materials_source_type'), table_name='materials')
    op.drop_column('materials', 'has_transcript')
    op.drop_column('materials', 'source_type')
    op.create_index(op.f('ix_quiz_attempts_course_id'), 'quiz_attempts', ['course_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_student_id'), 'quiz_attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_id'), 'student_enrollments', ['id'], unique=False)
    op.alter_column('topic_performance', 'mastery_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_topic_performance_course_id'), 'topic_performance', ['course_id'], unique=False)
    op.create_index(op.f('ix_topic_performance_student_id'), 'topic_performance', ['student_id'], unique=False)
    op.create_index(op.f('ix_tutor_interactions_session_id'), 'tutor_interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_tutor_interactions_student_id'), 'tutor_interactions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_interactions_student_id'), table_name='tutor_interactions')
    op.drop_index(op.f('ix_tutor_interactions_session_id'), table_name='tutor_interactions')
    op.drop_index(op.f('ix_topic_performance_student_id'), table_name='topic_performance')
    op.drop_index(op.f('ix_topic_performance_course_id'), table_name='topic_performance')
    op.alter_column('topic_performance', 'mastery_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_student_enrollments_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_quiz_attempts_student_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_course_id'), table_name='quiz_attempts')
    op.add_column('materials', sa.Column('source_type', postgresql.ENUM('YOUTUBE', 'GITHUB', 'ARXIV', 'BLOG', 'OER', 'DATASET', 'EXERCISE', 'MANUAL', name='sourcetype'), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('has_transcript', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_materials_source_type'), 'materials', ['source_type'], unique=False)
    op.alter_column('materials', 'embedding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_material_topics_material_id'), 'material_topics', ['material_id'], unique=False)
    op.drop_index(op.f('ix_material_ratings_id'), table_name='material_ratings')
    op.drop_index(op.f('ix_learning_sessions_student_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_course_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index('ix_course_materials_uploader', table_name='course_materials')
    op.drop_index(op.f('ix_course_materials_uploaded_by'), table_name='course_materials')
    op.drop_index(op.f('ix_course_materials_title'), table_name='course_materials')
    op.drop_index(op.f('ix_course_materials_id'), table_name='course_materials')
    op.drop_index(op.f('ix_course_materials_course_id'), table_name='course_materials')
    op.drop_index('ix_course_materials_course', table_name='course_materials')
    op.drop_table('course_materials')
    # ### end Alembic commands ###
